### ISSUE TITLE
When I try to run jakejs than I get this error

### ISSUE THREAD

**Issue by shahjehanali1** [jakejs/jake#343]
`jake aborted.
Error: Incorrect Node version; expected 0.12.7 but found v6.10.2
    at api.fail (C:\xampp\htdocs\SBConfig\node_modules\jake\lib\api.js:336:18)
    at Task.action (C:\xampp\htdocs\SBConfig\Jakefile.js:137:13)
(See full trace by running task with --trace)`

is there any solution?

**Comment by busticated** [comment]
pretty sure that error isn't coming from jake itself. rather jake is merely surfacing an underlying error encountered within one of its tasks. 

jake itself makes [no requirement around node version](https://github.com/jakejs/jake/blob/master/package.json#L36).

if you haven't already, take a look at the full trace via: `$jake --trace` to see if there's anything more helpful in the full stack.

otherwise, look at your dependencies (via your project's package.json) and see if any require node v0.12.x. from there you can either upgrade the dependency OR downgrade your node version.

fwiw, a google search for "Error: Incorrect Node version" turned this up --> https://github.com/jamesshore/object_playground/issues/6
