### ISSUE TITLE
Possible command injection in jake with publishTask

### ISSUE THREAD

**Issue by zpbrent** [jakejs/jake#391]
Hey, maintainers, I find a possible bug of command injection in your jake code. You can reproduce this bug by the following steps:
Step 1: create a jakefile.js with contents as below:
```
//jakefile.js
let { publishTask } = require('jake');
publishTask('abc', {gitCmd: '$(touch HACKED);'}, () => {});
//end of jakefile.js
```
Step 2: then run the shell code ``jake publish fetchTags`` in your terminal (guarantee you run the command in the same directory where the jakefile.js you created before resides), then the illegal file ``HACKED`` can be created. Note that, you can replace the injected command ``touch HACKED`` with any other OS commands.

I have reported this vul through huntr.dev at https://www.huntr.dev/bounties/1-npm-jake
As well as proposed a possible fix with a PR at https://github.com/418sec/jake/pull/1

Please help to confirm whether this is indeed a bug and also whether the fix you like, thanks!

**Comment by felix9** [comment]
Hi, thanks for the report, but I'm not sure I understand the problem.

Since a jakefile can already run arbitrary commands, I'm not sure how this is more vulnerable than that?

Consider the potential people involved:
1. The author of a jakefile can have it run arbitrary commands. There's no particular reason to limit what the author can express.
2. The user of a jakefile trusts the jakefile's author. If the user runs a jakefile from a malicious author, all bets are off. (This is not a problem to be ignored, but it's a large and complicated problem with no simple solution.)
3. Some 3rd person has a way to inject an unintended command when a user runs a jakefile from a trusted author.

It's the 3rd scenario that I think would need a security patch, and I'm not sure how that would happen in what you've described here?

**Comment by zpbrent** [comment]
> Hi, thanks for the report, but I'm not sure I understand the problem.
> 
> Since a jakefile can already run arbitrary commands, I'm not sure how this is more vulnerable than that?
> 
> Consider the potential people involved:
> 
> 1. The author of a jakefile can have it run arbitrary commands. There's no particular reason to limit what the author can express.
> 2. The user of a jakefile trusts the jakefile's author. If the user runs a jakefile from a malicious author, all bets are off. (This is not a problem to be ignored, but it's a large and complicated problem with no simple solution.)
> 3. Some 3rd person has a way to inject an unintended command when a user runs a jakefile from a trusted author.
> 
> It's the 3rd scenario that I think would need a security patch, and I'm not sure how that would happen in what you've described here?

Hi @felix9 , thanks for your quick response. 

Is it possible some authors share their jakefile within a nodejs package with others for building (e.g., some nodejs package is published and deliveried with a jakefile to allow the customers to build the package via jake in their local machie). If this case is possible, the malicious authors can inject arbitrary OS commands in the jakefile and the victims may run jakefile to build the package without knowing some malicious injected OS commands exectued as well?

**Comment by mde** [comment]
Jake by definition runs arbitrary JavaScript at the command line. This particular issue is not a vulnerability, in any way. Security is great and important, but I really wish people would stop with these bogus reports. At least understand what the tool is and how it works before reporting. This is a big waste of everyone's time.

**Comment by mattiaskagstrom** [comment]
This false-positive flags in OSS Sonatype:
https://ossindex.sonatype.org/component/pkg:npm/jake
